CREATE TABLE IF NOT EXISTS DUMMY_TABLE
(DUMMY_ID INT PRIMARY KEY AUTO_INCREMENT,
DUMMY_VALUE VARCHAR(255) );


INSERT INTO DUMMY_TABLE (DUMMY_VALUE) VALUES ('Sample Text 1');
INSERT INTO DUMMY_TABLE (DUMMY_VALUE) VALUES ('Sample Text 2');
